app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: root:Jassljy200507%@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 10
  MaxOpenConns: 100

redis:
  addr: "localhost:6379"
  type: 0
  password: ""